version: "3"

services:
  nginxproxy:
    depends_on:
      - server
      - client
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:3000"
    restart: always
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./https:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: server
    expose:
      - "3001"
    volumes:
      - ./https:/usr/share/nginx/html

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    volumes:
      - ./https:/usr/share/nginx/html

  cerbot:
    depends_on:
      - nginxproxy
    image: certbot/certbot
    container_name: cerbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./https:/usr/share/nginx/html
    command: --dry-run certonly --webroot --webroot-path=/usr/share/nginx/html --email siaksiakx@gmail.com --agree-tos --no-eff-email -d highlighters.site -d www.highlighters.site --force-renewal
