version: "3"

services:
  nginxproxy:
    depends_on:
      - server
      - client
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:3000"
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./myweb:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: server
    expose:
      - "3001"
    volumes:
      - ./myweb:/usr/share/nginx/html

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    volumes:
      - ./myweb:/usr/share/nginx/html

  # cerbot:
  #   depends_on:
  #     - nginxproxy
  #   image: certbot/certbot
  #   container_name: cerbot
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - ./myweb:/usr/share/nginx/html
  #   command: certonly --dry-run --webroot --webroot-path=/usr/share/nginx/html --email siaksiakxgmail.com --agree-tos --no-eff-email --keep-until-expiring -d highlighters.site -d www.highlighters.site
