version: "3"

services:
  nginxproxy:
    depends_on:
      - server
      - client
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:3000"
    restart: always
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./https:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: server
    expose:
      - "3001"
    volumes:
      - ./https:/usr/share/nginx/html
      - ./server/picture:/app/picture

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    volumes:
      - ./https:/usr/share/nginx/html

  # cerbot:
  #   depends_on:
  #     - nginxproxy
  #   image: certbot/certbot
  #   container_name: cerbot
  #   volumes:
  #     - ./certbot:/etc/letsencrypt
  #     - ./https:/usr/share/nginx/html
  #   command: --dry-run certonly --webroot --webroot-path=/usr/share/nginx/html --email siaksiakx@gmail.com --agree-tos --no-eff-email -d highlighters.site -d www.highlighters.site --force-renewal
#
# 인증서 재발급
# 1. docker-compose.yml에서 cerbot 주석 해제
# 2. nginx.conf에서 TLS 인증서 주석 해제
# 3. http -> https로 리다이렉트 주석 처리
